In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_auc_score
from featexp import univariate_plotter  # pip install featexp
from featexp import get_univariate_plots
from featexp import get_trend_stats

In [3]:
application_raw = pd.read_csv('application_train.csv')  # 银行贷款数据，预测违约可能性0/1
application_raw.head()

   SK_ID_CURR  TARGET NAME_CONTRACT_TYPE  ... AMT_REQ_CREDIT_BUREAU_QRT AMT_REQ_CREDIT_BUREAU_YEAR     DATE
0      145457       0         Cash loans  ...                       0.0                        2.0  2018-05
1      128979       0         Cash loans  ...                       0.0                        3.0  2018-05
2      145448       0         Cash loans  ...                       0.0                        5.0  2018-03
3      294475       0         Cash loans  ...                       0.0                        1.0  2018-04
4      216609       0    Revolving loans  ...                       0.0                        0.0  2018-03

[5 rows x 123 columns]

In [ ]:
# 数据预处理
def get_nonull_dummy_data(application_train_raw, dummy_drop=['ORGANIZATION_TYPE']):
    # 缺失值填充
    nulls = pd.isnull(application_train_raw),sum()
    less_nulls = nulls[(nulls<3075)&(nulls!=0)].index
    less_nulls_float = []
    for i in range(len(less_nulls)):
        if application_train_raw[less_nulls[i]].dtype!='0':
            less_nulls_float.append(less_nulls[i])
            
    application_train_raw[less_nulls_float] = application_train_raw[less_nulls_float].fillna(application_train_raw[less_nulls_float].mean())
    
    # 缺失值填充
    more_nulls = nulls[(nulls >= 3075)].index
    more_nulls_float = []
    for i in range(len(more_nulls)):
        if application_train_raw[more_nulls[i]].dtype!='0':
            more_nulls_float.append(more_nulls[i])
            
    application_train_raw[more_nulls_float] = application_train_raw[more_nulls_float].fillna(application_train_raw[more_nulls_float].mean())
    
    # 特征编码
    application_train_raw.drop(columns=dummy_drop, axis=1, inplace=True)
    
    all_cols = application_train_raw.columns
    cat_cols = []
    for col in all_cols:
        if application_train_raw[col].dtype!='0':
            more_nulls_float.append(col)
            
    application_train_raw = pd.get_dummies(application_train_raw,columns=cat_cols, axis=1, dummy_na=True)
    
    return application_train_raw


def import_and_create_train_test_data(test_size=0.33, random_state=42):
    application_raw = pd.read_csv('application_train.csv') 
    application = get_nonull_dummy_data(application_raw, dummy_drop=['ORGANIZATION_TYPE'])
    
    X = application.drop(['TARGET'],axis=1)
    y = application['TARGET']
    X_train, X_test,y_train,y_test = train_test_split(X, y, test_size=test_size,random_state=random_state)
    
    train_users = X_train[['SK_ID_CURR']]
    train_users['TARGET'] = y_train
    test_users = X_test[['SK_ID_CURR']]
    test_users['TARGET'] = y_test
    train_users.reset_index(drop=True, inplace=True)
    test_users.reset_index(drop=True, inplace=True)
    
    return(X_train, X_test,y_train,y_test,train_users,test_users)


def import_and_create_TEST_data():
    application_raw = pd.read_csv('test_data.csv') 
    application = get_nonull_dummy_data(application_raw, dummy_drop=['ORGANIZATION_TYPE'])
  
    X = application
    users = X[['SK_ID_CURR']]